/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SystemsIndexRouteImport } from './routes/systems.index'
import { Route as SystemsSlugRouteImport } from './routes/systems.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsIndexRoute = SystemsIndexRouteImport.update({
  id: '/systems/',
  path: '/systems/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsSlugRoute = SystemsSlugRouteImport.update({
  id: '/systems/$slug',
  path: '/systems/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/blog': typeof BlogRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/systems/$slug': typeof SystemsSlugRoute
  '/systems/': typeof SystemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/blog': typeof BlogRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/systems/$slug': typeof SystemsSlugRoute
  '/systems': typeof SystemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/blog': typeof BlogRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/systems/$slug': typeof SystemsSlugRoute
  '/systems/': typeof SystemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/apply'
    | '/blog'
    | '/case-studies'
    | '/contact'
    | '/industries'
    | '/sitemap.xml'
    | '/systems/$slug'
    | '/systems/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/apply'
    | '/blog'
    | '/case-studies'
    | '/contact'
    | '/industries'
    | '/sitemap.xml'
    | '/systems/$slug'
    | '/systems'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/apply'
    | '/blog'
    | '/case-studies'
    | '/contact'
    | '/industries'
    | '/sitemap.xml'
    | '/systems/$slug'
    | '/systems/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApplyRoute: typeof ApplyRoute
  BlogRoute: typeof BlogRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  IndustriesRoute: typeof IndustriesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SystemsSlugRoute: typeof SystemsSlugRoute
  SystemsIndexRoute: typeof SystemsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems/': {
      id: '/systems/'
      path: '/systems'
      fullPath: '/systems/'
      preLoaderRoute: typeof SystemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems/$slug': {
      id: '/systems/$slug'
      path: '/systems/$slug'
      fullPath: '/systems/$slug'
      preLoaderRoute: typeof SystemsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApplyRoute: ApplyRoute,
  BlogRoute: BlogRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  IndustriesRoute: IndustriesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SystemsSlugRoute: SystemsSlugRoute,
  SystemsIndexRoute: SystemsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
